catalogs:
  build:
    "@astrojs/sitemap": ^3.6.0
    "@unocss/reset": ^66.5.4
    lightningcss: ^1.30.2
    unocss: 66.2.2
  dev:
    lint-staged: ^16.2.5
    simple-git-hooks: ^2.13.1
    wrangler: ^4.43.0
  frontend:
    "@iconify-json/carbon": ^1.2.14
    "@iconify-json/devicon": ^1.2.45
    "@iconify-json/simple-icons": ^1.2.55
    "@astrojs/mdx": ^4.3.7
    astro: ^5.14.7
    dayjs: ^1.11.18
    rehype-autolink-headings: ^7.1.0
    rehype-slug: ^6.0.0
  lint:
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1

onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - workerd
