catalogs:
  build:
    '@astrojs/sitemap': ^3.5.1
    '@unocss/reset': ^66.4.2
    lightningcss: ^1.30.1
    unocss: 66.2.2
  dev:
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    wrangler: ^4.32.0
  frontend:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/devicon': ^1.2.42
    '@iconify-json/simple-icons': ^1.2.49
    '@astrojs/mdx': ^4.3.4
    astro: ^5.13.3
    dayjs: ^1.11.13
    rehype-autolink-headings: ^7.1.0
    rehype-slug: ^6.0.0
  lint:
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1

onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - workerd
