catalogs:
  build:
    "@astrojs/sitemap": ^3.6.0
    lightningcss: ^1.30.2
    unocss: 66.2.2
  dev:
    wrangler: ^4.46.0
    lefthook: ^2.0.2
  frontend:
    "@iconify/json": ^2.2.404
    "@astrojs/mdx": ^4.3.9
    astro: ^5.15.3
    dayjs: ^1.11.19
    rehype-autolink-headings: ^7.1.0
    rehype-slug: ^6.0.0
  lint:
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd
