catalogs:
  build:
    '@astrojs/sitemap': ^3.7.0
    unocss: 66.2.2
  dev:
    wrangler: ^4.62.0
    lefthook: ^2.0.16
  frontend:
    '@iconify/json': ^2.2.435
    '@astrojs/mdx': ^4.3.13
    astro: ^5.17.1
    dayjs: ^1.11.19
  lint:
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd
