catalogs:
  build:
    "@astrojs/sitemap": ^3.6.0
    lightningcss: ^1.30.2
    unocss: 66.2.2
  dev:
    wrangler: ^4.43.0
    lefthook: ^2.0.0
  frontend:
    "@iconify/json": ^2.2.398
    "@astrojs/mdx": ^4.3.7
    astro: ^5.14.7
    dayjs: ^1.11.18
    rehype-autolink-headings: ^7.1.0
    rehype-slug: ^6.0.0
  lint:
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - workerd
